apiVersion: apps/v1
kind: Deployment
metadata:
  name: playground
  namespace: dev
  labels:
    my_label: deployment-label
spec:
  replicas: 2
  selector:
    matchLabels:
      my_label: playground-label
  template:
    metadata:
      labels:
        my_label: playground-label
    spec:
      containers:
      - name: playground
        image: wil42/playground:v1
        ports:
        - containerPort: 8888
