apiVersion: v1
kind: Service
metadata:
  name: playground
  namespace: dev
  lables:
    my_label: service-label
spec:
  type: ClusterIP
  selector:
    my_label: playground-label
  ports:
  - port: 8888
    targetPort: 8888
